stages:
  - install
  - test

variables:
  NODE_ENV: test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install

run_tests:
  stage: test
  script:
    - npm test
